name = "SnowballStemmer"
uuid = "0089d5a0-cc9e-11e8-15b2-431392cf18df"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.1.1"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
